### ISSUE TITLE
希望能将青龙最新版2.15.8内置的python版本从3.10降低到3.9

### ISSUE THREAD

**Issue by yxnwh** [whyour/qinglong#1832]
### Clear and concise description of the problem

安装ddddocr依赖时，需要3.6≤python≤3.9

### Suggested solution

希望能将内置的python版本降低到3.9，后续青龙版本升级时，也不要升级了。。。。99%的依赖库都能支持python3.9

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
https://github.com/sml2h3/ddddocr  不是早支持 3.10 了

**Comment by 2331892928** [comment]
![Uploading image.png…]()


> https://github.com/sml2h3/ddddocr 不是早支持 3.10 了

**Comment by 2331892928** [comment]
> https://github.com/sml2h3/ddddocr 不是早支持 3.10 了

The conflict is caused by:                                                      
    ddddocr 1.4.8 depends on onnxruntime                                        
    ddddocr 1.4.7 depends on onnxruntime                                        
    ddddocr 1.4.6 depends on onnxruntime                                        
    ddddocr 1.4.5 depends on onnxruntime                                        
    ddddocr 1.0.6 depends on onnxruntime                                        
                                                                                
To fix this you could try to:                                                   
1. loosen the range of package versions you've specified                        
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by wsgehaishan520** [comment]
onnxruntime 这个依赖怎么安装成功呀
